# Generated by Django 4.0.6 on 2022-07-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogsandowner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='type',
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsandowner.owner')),
            ],
            options={
                'db_table': 'dogs',
            },
        ),
    ]
