# Generated by Django 4.0.6 on 2022-07-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsandowner', '0002_remove_owner_dog_remove_owner_name_remove_owner_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=2),
        ),
    ]
